# Remove any languages you don't want analyzed.
languages:
  Python: true
exclude_paths:
- "*/src/test/*"
- "*/test/*"
# - app/helpers/users_helper.php # Exclude a specific file
# - app/controllers/* # Exclude all contents of a folder (including all subfolders)
# - app/controllers/*.py # Exclude specific files type within a folder/subfolders
# - lib/**/*.rb # Recursively ignore all files ending in .rb
